---
- include:                      '../tasks/install_packages.yml'
- include:                      '../tasks/known_hosts.yml'
  vars:
    known_hosts:
      - "{{ backup_server }}"
  with_items:                   "{{ groups['backup_server'] }}"
  loop_control:
    loop_var:                   backup_server
- include:                      '../tasks/users.yml'
  vars:
    users:
      - "{{ backup_client_user }}"
  with_items:                   "{{ hostvars[inventory_hostname]['backup_client_users'] }}"
  loop_control:
    loop_var:                   backup_client_user
- include:                      '../tasks/create_files.yml'
  vars:
    create_files:
      - owner:                  "{{ backup_client_user }}"
        group:                  "{{ backup_client_user }}"
        mode:                   '0700'
        state:                  'directory'
        path:                   "~{{ backup_client_user }}/.ssh"
      - owner:                  "{{ backup_client_user }}"
        group:                  "{{ backup_client_user }}"
        mode:                   '0640'
        state:                  'touch'
        path:                   "/var/log/backup-for-{{ backup_client_user }}.log"
      - owner:                  "{{ backup_client_user }}"
        group:                  "{{ backup_client_user }}"
        mode:                   '0644'
        state:                  'touch'
        path:                   "/var/log/backup-for-{{ backup_client_user }}.ret"
  with_items:                   "{{ hostvars[inventory_hostname]['backup_client_users'] }}"
  loop_control:
    loop_var:                   backup_client_user
- include:                      '../tasks/install_files.yml'
  vars:
    install_files:
      - owner:                  "{{ backup_client_user }}"
        group:                  "{{ backup_client_user }}"
        mode:                   '0600'
        src:                    "../../sensitive_ansible/inventory/hosts/{{ inventory_hostname }}/users/{{ backup_client_user }}/files/ssh_keys/id_rsa"
        dest:                   "~{{ backup_client_user }}/.ssh/id_rsa"
  with_items:                   "{{ hostvars[inventory_hostname]['backup_client_users'] }}"
  loop_control:
    loop_var:                   backup_client_user
- include:                      '../tasks/install_files.yml'
  vars:
    install_files:
      - owner:                  "{{ backup_client_user }}"
        group:                  "{{ backup_client_user }}"
        mode:                   '0644'
        src:                    "../inventory/hosts/{{ inventory_hostname }}/users/{{ backup_client_user }}/files/ssh_keys/id_rsa.pub"
        dest:                   "~{{ backup_client_user }}/.ssh/id_rsa.pub"
  with_items:                   "{{ hostvars[inventory_hostname]['backup_client_users'] }}"
  loop_control:
    loop_var:                   backup_client_user
- include:                      '../tasks/template_files.yml'
  vars:
    template_files:
      - owner:                  'root'
        group:                  "{{ backup_client_user }}"
        mode:                   '0750'
        src:                    'templates/bin/backup-for-user.j2'
        dest:                   "/usr/local/bin/backup-for-{{ backup_client_user }}"
  with_items:                   "{{ hostvars[inventory_hostname]['backup_client_users'] }}"
  loop_control:
    loop_var:                   backup_client_user
- include:                      '../tasks/template_files.yml'
  vars:
    template_files:
      - owner:                  'root'
        group:                  'root'
        mode:                   '0644'
        src:                    'templates/cron.d/backup-for-user.j2'
        dest:                   "/etc/cron.d/backup-for-{{ backup_client_user }}"
  with_items:                   "{{ hostvars[inventory_hostname]['backup_client_users'] }}"
  loop_control:
    loop_var:                   backup_client_user
